[package]
name = "sudix"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
nix.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true

[[bin]]
name = "sudixd"
path = "src/bin/sudixd.rs"

[[bin]]
name = "sudix"
path = "src/bin/sudix.rs"

[lints]
workspace = true
